### PR TITLE
[IMP] purchase_advance_payment: Add attachments button in tree view of payments

### PR DESCRIPTION
**Pull request by EmilioSerna**
Task: https://www.vauxoo.com/web#action=464&active_id=200&cids=1&id=71294&menu_id=1490&model=project.task&view_type=form

PR Related: https://github.com/Vauxoo/lavop/pull/79

Instance: https://www.odoo.sh/project/lavop/branches/15.0-lavop-imp-atts-emilioserna

Improvements:

- Fix where payments weren't relating to the purchase orders when registering payments to multiple moves.
- Fix where the payment status for the order was changing to "partially paid" even though it didn't have any payments yet.
- Improvement to add an attachment button to the tree view in payments.

image
image

### CODE REVIEW

**Comment by EmilioSerna** [comment]
Hi @hugho-ad 

Could you please review?

Thanks!

cc @angelesgl17

**Comment by angelesgl17** [comment]
+1 @EmilioSerna 

@hugho-ad could u please review this?

Thanks!

**Review by hugho-ad — APPROVED** [review]

**Comment by hugho-ad** [comment]
LGTM :+1: 

@EmilioSerna 
could you open a new PR to the oca repo with all these changes at branch 15.0-lavop please?

**Comment by EmilioSerna** [comment]
> LGTM 👍
> 
> @EmilioSerna could you open a new PR to the oca repo with all these changes at branch 15.0-lavop please?

Done!
https://github.com/OCA/purchase-workflow/pull/1989

**Pull request merged**
