### PR TITLE
[FIX] purchase_discount: Fix undefined argument on purchase_discount: original function use move=False and inherited function just use move

### PR DESCRIPTION
**Pull request by rolandojduartem**
The original code, with no stock_landed_costs installed, caused the following error https://gist.github.com/rolandojduartem/64f4c0775d1eb11ff9c6bcfda02b94be at the moment to create an invoice from a purchase order. This code fix that error. The original function is https://github.com/odoo/odoo/blob/14.0/addons/purchase/models/purchase.py#L1143

purchase-wokflow_fix

### CODE REVIEW

**Comment by rolandojduartem** [comment]
Hi, @luisg123v, @hugho-ad and @moylop260, Could someone review this fix on purchase_discount. the pre - commit failed but it was because of the environment and not because of a module error?

**Review by luisg123v — CHANGES_REQUESTED** [review]
Hi @rolandojduartem,

Please:
- Target OCA/purchase-workflow instead of vauxoo/purchase-workflow
- PR & commit's title should contain the module name, in this case `purchase_discount`, instead of `purchase-workflow`
- Folowing -> following

**Comment by desdelinux** [comment]
Solved: https://github.com/OCA/purchase-workflow/blob/14.0/purchase_discount/models/purchase_order.py#L108

https://github.com/OCA/purchase-workflow/pull/1108

**Comment by rolandojduartem** [comment]
Closed by https://github.com/Vauxoo/purchase-workflow/commit/0388fadbbd415163bc42776a38ea860ff982f8b9

**Pull request closed without merging**
